/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface TimeCapsuleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "canUnlock"
      | "capsules"
      | "createCapsule"
      | "decryptManager"
      | "getCapsule"
      | "getTotalCapsules"
      | "getUserCapsules"
      | "protocolId"
      | "userCapsules"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "CapsuleCreated" | "CapsuleUnlocked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "canUnlock",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "capsules",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createCapsule",
    values: [BytesLike, BytesLike, BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "decryptManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCapsule",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalCapsules",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserCapsules",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "userCapsules",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "canUnlock", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "capsules", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createCapsule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "decryptManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getCapsule", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTotalCapsules",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserCapsules",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userCapsules",
    data: BytesLike
  ): Result;
}

export namespace CapsuleCreatedEvent {
  export type InputTuple = [
    capsuleId: BigNumberish,
    creator: AddressLike,
    unlockTimestamp: BigNumberish
  ];
  export type OutputTuple = [
    capsuleId: bigint,
    creator: string,
    unlockTimestamp: bigint
  ];
  export interface OutputObject {
    capsuleId: bigint;
    creator: string;
    unlockTimestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CapsuleUnlockedEvent {
  export type InputTuple = [capsuleId: BigNumberish, creator: AddressLike];
  export type OutputTuple = [capsuleId: bigint, creator: string];
  export interface OutputObject {
    capsuleId: bigint;
    creator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TimeCapsule extends BaseContract {
  connect(runner?: ContractRunner | null): TimeCapsule;
  waitForDeployment(): Promise<this>;

  interface: TimeCapsuleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  canUnlock: TypedContractMethod<[capsuleId: BigNumberish], [boolean], "view">;

  capsules: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, string, boolean] & {
        encryptedMessagePart1: string;
        encryptedMessagePart2: string;
        unlockTimestamp: bigint;
        creator: string;
        exists: boolean;
      }
    ],
    "view"
  >;

  createCapsule: TypedContractMethod<
    [
      encMessagePart1: BytesLike,
      messagePart1Proof: BytesLike,
      encMessagePart2: BytesLike,
      messagePart2Proof: BytesLike,
      unlockTimestamp: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  decryptManager: TypedContractMethod<[], [string], "view">;

  getCapsule: TypedContractMethod<
    [capsuleId: BigNumberish],
    [
      [string, string, bigint, string, boolean] & {
        encryptedMessagePart1: string;
        encryptedMessagePart2: string;
        unlockTimestamp: bigint;
        creator: string;
        exists: boolean;
      }
    ],
    "view"
  >;

  getTotalCapsules: TypedContractMethod<[], [bigint], "view">;

  getUserCapsules: TypedContractMethod<[user: AddressLike], [bigint[]], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  userCapsules: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "canUnlock"
  ): TypedContractMethod<[capsuleId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "capsules"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, string, boolean] & {
        encryptedMessagePart1: string;
        encryptedMessagePart2: string;
        unlockTimestamp: bigint;
        creator: string;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "createCapsule"
  ): TypedContractMethod<
    [
      encMessagePart1: BytesLike,
      messagePart1Proof: BytesLike,
      encMessagePart2: BytesLike,
      messagePart2Proof: BytesLike,
      unlockTimestamp: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "decryptManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getCapsule"
  ): TypedContractMethod<
    [capsuleId: BigNumberish],
    [
      [string, string, bigint, string, boolean] & {
        encryptedMessagePart1: string;
        encryptedMessagePart2: string;
        unlockTimestamp: bigint;
        creator: string;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalCapsules"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserCapsules"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "userCapsules"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "CapsuleCreated"
  ): TypedContractEvent<
    CapsuleCreatedEvent.InputTuple,
    CapsuleCreatedEvent.OutputTuple,
    CapsuleCreatedEvent.OutputObject
  >;
  getEvent(
    key: "CapsuleUnlocked"
  ): TypedContractEvent<
    CapsuleUnlockedEvent.InputTuple,
    CapsuleUnlockedEvent.OutputTuple,
    CapsuleUnlockedEvent.OutputObject
  >;

  filters: {
    "CapsuleCreated(uint256,address,uint256)": TypedContractEvent<
      CapsuleCreatedEvent.InputTuple,
      CapsuleCreatedEvent.OutputTuple,
      CapsuleCreatedEvent.OutputObject
    >;
    CapsuleCreated: TypedContractEvent<
      CapsuleCreatedEvent.InputTuple,
      CapsuleCreatedEvent.OutputTuple,
      CapsuleCreatedEvent.OutputObject
    >;

    "CapsuleUnlocked(uint256,address)": TypedContractEvent<
      CapsuleUnlockedEvent.InputTuple,
      CapsuleUnlockedEvent.OutputTuple,
      CapsuleUnlockedEvent.OutputObject
    >;
    CapsuleUnlocked: TypedContractEvent<
      CapsuleUnlockedEvent.InputTuple,
      CapsuleUnlockedEvent.OutputTuple,
      CapsuleUnlockedEvent.OutputObject
    >;
  };
}
